<?php

namespace AppBundle\Repository;

/**
 * BatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRepository extends \Doctrine\ORM\EntityRepository
{
}
