<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByBatchId($batchId){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from($this->_entityName, 's')
            ->where('s.batchId = :batiId')
            ->setParameter('bathId', $batchId);

        return $qb->getQuery()->getResult();
    }
}
