<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByBatchId($batchId){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from($this->_entityName, 's')
            ->where('s.batchId = :batchId')
            ->setParameter('batchId', $batchId);

        return $qb->getQuery()->getResult();
    }

    public function findByTeacherId($teacherId){
        $qb = $this->_em->createQueryBuilder();
            $qb->select('session')
            ->from($this->_entityName, 'session')
            ->leftJoin('session.module', 'module')
            ->where('module.teacher = :teacherId')
            ->setParameter('teacherId', $teacherId);

        return $qb->getQuery()->getResult();
    }
}
